apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: zeuslawyer/comments
---
# add a Cluster IP service object to this comments deployment
apiVersion: v1
kind: Service
metadata:
  name: comments-clusterip # name of this Cluster IP Service.
spec:
  type: ClusterIP
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 5002
      targetPort: 5002
