name: auth-tests

on:
  pull_request:
    paths:
      - project_final_stubhub/auth/** # only run when changes are in this directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd project_final_stubhub/auth && yarn install && yarn run test:ci
 
