name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "project_final_stubhub/auth/**"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #checkout all the code in the repo
      - run: cd project_final_stubhub/auth && docker build -t zeuslawyer/project_final_auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
